export const postTagOptions = [
  { title: "freedom", value: "freedom" },
  { title: "intentional living", value: "intentional living" },
  { title: "modern life", value: "modern life" },
  { title: "financial independence", value: "financial independence" },
  { title: "systems", value: "systems" },
  { title: "routine", value: "routine" },
  { title: "income", value: "income" },
  { title: "spending", value: "spending" },
  { title: "lifestyle inflation", value: "lifestyle inflation" },
  { title: "enough", value: "enough" },
  { title: "work culture", value: "work culture" },
  { title: "money mindset", value: "money mindset" },
  { title: "investing", value: "investing" },
  { title: "saving", value: "saving" },
  { title: "compound interest", value: "compound interest" },
  { title: "portfolio", value: "portfolio" },
  { title: "tools", value: "tools" },
  { title: "fire strategy", value: "fire strategy" },
];
